### ISSUE TITLE
Ability to right-click Create Contract in the Contract Explorer view

### ISSUE THREAD

**Issue by kevinbluer** [trufflesuite/vscode-ext#105]
Low-ish priority, but it would be useful to be able to right-click Create Contract in this view to save you having to jump back over to the Explorer tab.

<img width="249" alt="Screen Shot 2022-06-08 at 3 30 27 PM" src="https://user-images.githubusercontent.com/210755/172711618-fc0b34a7-238d-449c-baf0-9ca25f678437.png">

**Comment by xhulz** [comment]
@kevinbluer this issue was solved here: https://github.com/trufflesuite/vscode-ext/pull/104

Just waiting @michaeljohnbennett approval to be merged

**Comment by xhulz** [comment]
@kevinbluer & @michaeljohnbennett thanks for your approval. It has merged :)

**Comment by NikolaiSch** [comment]
If it’s ok @kevinbluer, I would like to complete this, I’ll get started on a pull request, in order to become more familiar with the VS code api. Thanks :)

**Comment by kevinbluer** [comment]
Hey @NikolaiSch, apologies for the slight delay (was offline yesterday), but that would be awesome! Just assigned you now. Let us know if you have any questions as you dig in. Thanks again 👍

**Comment by NikolaiSch** [comment]
@kevinbluer no problem, was busy yesterday and today anyway, when i'm home from rust london talk, i'll start work!

**Comment by kevinbluer** [comment]
Awesome 🙌 Also hope the rust talk was good!

**Comment by NikolaiSch** [comment]
@kevinbluer, it was :).

I am not sure why
`await tryExecute(() => ServiceCommands.createProject());`
is used instead of just
`await tryExecute(ServiceCommands.createProject);`

is there a reason?

**Comment by NikolaiSch** [comment]
if anyone can have a look and comment upon my pull request, i would be greatful :). @kevinbluer @michaeljohnbennett. I would love to continue to contribute to this project!

**Comment by kevinbluer** [comment]
Hey @NikolaiSch, quick heads up that `v2.4` (with your contribution) is now in live 🥳 See the [announcement](https://github.com/orgs/trufflesuite/discussions/5364) for more details.

Thanks again and more contributions always welcome!
