### ISSUE TITLE
spawn C:\WINDOWS\system32\cmd.exe ENOENT

### ISSUE THREAD

**Issue by xxll88** [trufflesuite/vscode-ext#108]
when build contract  and running command   "npx truffle compile" , a window pops up  : "spawn C:\WINDOWS\system32\cmd.exe ENOENT" , 2.21 is ok , 2.3.1 and 2.3.3 have same problem

**Comment by michaeljohnbennett** [comment]
Thanks for letting us know.

Can you give us some more background on this bug:

1. Does this work ok in the folder on the command line? Without using VSCode.
2. Can you give us the output from the output channel on the vscode extension to see what errors its outputting, if any. https://trufflesuite.com/docs/vscode-ext/installation-guide/#help-i-still-have-problems on how to get this.
3. What version of Node/NPM are you using?

**Comment by xxll88** [comment]
1.Does this work ok in the folder on the command line? Without using VSCode.
ans：    yes ，run truffle compile in terminal is ok

Can you give us the output from the output channel on the vscode extension to see what errors its outputting, if any. https://trufflesuite.com/docs/vscode-ext/installation-guide/#help-i-still-have-problems on how to get this.
 ans：  when start  build contract,  vscode output window has some nomal infomations  until  diaplays  "npx truffle compile" ,pop a box with red font "spawn C:\WINDOWS\system32\cmd.exe ENOENT", nevertheless terminal window run C:\WINDOWS\system32\cmd.exe is ok.

What version of Node/NPM are you using?
ans:  windows 11 with node 16.15.1 ,npm 6.14.17 (npm 8 can't install -g truffle, 
downgrage to npm@6)
i have two computers with above environment :
windows2019 server is ok with  truffle vscode -ext 2.3.3
windows 11 is ok only with 2.2.1

**Comment by michaeljohnbennett** [comment]
Thank you for all this info, we have some VM's with different versions of windows we can test on here, and see if we can replicate the issue on the latest extension.

**Comment by xhulz** [comment]
Hi @xxll88 and @FILAgiao!

Thank you for reaching out :) Please, is it possible execute the command "build contracts" again and send us the log, like the image below?

<img width="1722" alt="Screenshot 2022-06-14 at 15 45 43" src="https://user-images.githubusercontent.com/32708942/173675971-89d98ef4-ddc9-4963-88a6-a019919f5015.png">

**Comment by xxll88** [comment]
![image](https://user-images.githubusercontent.com/54157661/173716577-328ef83f-f541-45b2-b35c-c0901a6ed677.png)

**Comment by xhulz** [comment]
Thank you @xxll88!

We are working on that :)

**Comment by michaeljohnbennett** [comment]
We have made a release v2.3.4 to the marketplace and this should resolve the issues you were seeing, please let us know how you get on.

Reopen this issue if the problem still persists after updating the extension to the latest release version.
