### ISSUE TITLE
Unable to detect Installed Node.Js Current 18.4.0

### ISSUE THREAD

**Issue by kaustubh135** [trufflesuite/vscode-ext#115]
I am using windows 11, I have installed all other dependencies including node which was already installed but when I try using Truffle: New Solidity Project command in VS Code it gives me error "To run command you should install required apps. Please see details on the Requirements Page" after opening the details I can see option to install Node.Js even though it is still installed and added to PATH.

Installed Versions:
Truffle for VS Code: 2.3.4
VS Code: 1.68.1
Node.Js: 18.4.0 Current

![2022-06-30_14 52 47_Code](https://user-images.githubusercontent.com/90188030/176642309-8ab7be49-515c-4be8-a448-f7ab30531464.png)

**Comment by xhulz** [comment]
Hi @kaustubh135!

Thank you so much for letting us know about that. Today the code is limiting the node version from 14.0.0 to 17.0.0 but let me check if we can increase this range and release a new extension version.

As soon as I have an answer, I'll let you know :)

Thank you again

**Comment by xhulz** [comment]
Hi @kaustubh135!

I've checked the information. Truffle is not ready to run over node 18+. Today, we recommend using version between 14 and 17. We are working on migrating to node 18+, but for now we don't have a release date.

Thanks again for your contact :)

**Comment by xhulz** [comment]
I'm gonna close this issue, but feel free to reopen in any case.

Thanks!
