### ISSUE TITLE
In the Sidebar rename "Truffle - Explorer" to "Contract Explorer"

### ISSUE THREAD

**Issue by kevinbluer** [trufflesuite/vscode-ext#121]
The use of the "Truffle" prefix is somewhat redundant and "Contract Explorer" disambiguates it from the "Explorer" tab / view.

<img width="202" alt="Screen Shot 2022-07-01 at 5 02 15 PM" src="https://user-images.githubusercontent.com/210755/176972562-018c134e-7ac4-4522-980b-adad8bd5e262.png">

**Comment by acuarica** [comment]
Fixed in #122. Thanks @NikolaiSch!
