### ISSUE TITLE
Should switch from JQuery to reduce size?

### ISSUE THREAD

**Issue by NikolaiSch** [trufflesuite/vscode-ext#124]
Is there is any reason to continue using jquery instead of a smaller framework, for example Svelte for that single page app in `/resources/welcome`?

I have experience in web development, so if you would want me to rewrite it to minimise size, let me know

**Comment by NikolaiSch** [comment]
@kevinbluer, ill get a quick mockup of a suggestion, just so you can see whether or not its a logical improvement.

**Comment by michaeljohnbennett** [comment]
sure, give it a shot, I think this is quite an older historical choice for the page and elements. Will need to see how this interacts with the typescript backing files as these pages act akin to an MVC style app.

**Comment by NikolaiSch** [comment]
I have one question, where is the acquireVsCodeApi() function defined? is that a native vscode api that is provided?

**Comment by michaeljohnbennett** [comment]
I think so, the engine has an api, it will be documented in the VSCode API docs somewhere. I'm not exactly sure where.

**Comment by acuarica** [comment]
Hey @NikolaiSch, a quick heads up, we removed `jQuery` from the extension. See https://github.com/trufflesuite/vscode-ext/pull/284 for more details. Moreover, you can check https://github.com/trufflesuite/vscode-ext/issues/269 to see our efforts to reduce the extension size.
