### ISSUE TITLE
Node.js is not detected as installed globally even if it is on MacOs

### ISSUE THREAD

**Issue by Blu3Jy** [trufflesuite/vscode-ext#128]
The extension does not detect Node as installed

Mac Os Monterey 12.4 (21F79)

npm list -g --depth 0
/Users/useruser/.nvm/versions/node/v17.7.2/lib
├── corepack@0.11.2
├── ganache@7.3.2
├── ipfs@0.63.5
├── npm@8.13.2
└── truffle@5.5.20

node --version
v17.7.2

nvm --version
0.39.1

The Node LTS version also does not work, VS Code does not see it.

**Comment by xhulz** [comment]
Hey @Blu3Jy!

Thank you so much for reaching out to us.

Today the Truffle VSCode extension is limiting the node version between 14.0.0 and 17.0.0.

FYI, this problem was related here: https://github.com/trufflesuite/vscode-ext/issues/115

Thanks!

**Comment by Blu3Jy** [comment]
Yeah thanks, i was also able to figure it out, here is a Stackexchange question that addresses the same issue.

https://ethereum.stackexchange.com/questions/129301/why-vs-code-not-recognizing-the-node-version/131301#131301

I think it's important to note that i had to specify the default alias node version to "lts/*" in order for VS Code to recognise it, because when i had tried to use a version between 14 and 17 but didn't specify the alias, VSCode would not recognise it. (even if i had doubled checked that the running node version in use was indeed the 16 at the time of the test)

Now after specifying it it works.

**Comment by xhulz** [comment]
Hi @Blu3Jy!

Thank you again for letting us know about the "lts/*". We are investigating it :)

In the meantime, we are preparing a new release with more information about the min/max versions.

I'm gonna close this issue, but feel free to open it again anytime :)

Cheers!

**Comment by HoneyIsMoney** [comment]
> Hi @Blu3Jy!
> 
> Thank you again for letting us know about the "lts/*". We are investigating it :)
> 
> In the meantime, we are preparing a new release with more information about the min/max versions.
> 
> I'm gonna close this issue, but feel free to open it again anytime :)
> 
> Cheers!

im having the same issue, the extention is not recognising my version of node. i have tried @Blu3Jy sugestion however this is still not working for me. ive installed the LTS version and set it as the default with `nvm alias default "lts/*"` but still no joy

i am using 
- MacOs Monteray `12.4`
- nvm `0.38.0`
- node LTS `16.16.0`
- zsh

**Comment by A-F-V** [comment]
I am having the same problem. The issue I believe is that if you have another version of node running that you got through brew (to nvm that is `system` version) that is being prioritized and is outside the range of 14 to 17
