### ISSUE TITLE
"Show Smart Contract Interaction Page" missing

### ISSUE THREAD

**Issue by Blu3Jy** [trufflesuite/vscode-ext#129]
There is no "Show Smart Contract Interaction Page" button even after building and deploying to ganache.

<img width="315" alt="Screenshot 2022-07-07 at 18 04 40" src="https://user-images.githubusercontent.com/102261403/177819872-23d12fa3-8cca-4239-9cd5-6c57c66e1997.png">

System info:
Macbook Air M1 16gb unified memory - 512 GB Storage
Mac Os Monterey 12.4 (21F79)

**Comment by kevinbluer** [comment]
Hey @Blu3Jy, thanks for reaching out! Can you confirm where you saw the reference to that feature as it's been deprecated for a while now (although it's something that should be coming back in [Truffle Dashboard](https://trufflesuite.com/docs/truffle/getting-started/using-the-truffle-dashboard/) quite soon).

In the interim, one alternative approach to interacting with your contracts is via `truffle console` (documentation [here](https://trufflesuite.com/docs/truffle/getting-started/using-truffle-develop-and-the-console/)). Hopefully that helps and let us know if you have any questions with using it.

**Comment by Blu3Jy** [comment]
Found it here:

https://trufflesuite.com/docs/vscode-ext/interacting-with-your-smart-contract/#interact-with-your-contract

**Comment by kevinbluer** [comment]
Argh, good spot! That page should technically been removed when the feature was depreciated (will get it removed shortly). Super sorry for any confusion.

As mentioned, any assistance with interacting with your contracts via the console, just let us know either on this thread or a new [Github discussion](https://github.com/orgs/trufflesuite/discussions).
