### ISSUE TITLE
CI status icon broken on README / marketplace page

### ISSUE THREAD

**Issue by kevinbluer** [trufflesuite/vscode-ext#130]
See the following:

<img width="310" alt="Screen Shot 2022-07-07 at 4 09 18 PM" src="https://user-images.githubusercontent.com/210755/177872085-41ac3147-1a0a-46a5-88cc-81c6b29621a1.png">

**Comment by michaeljohnbennett** [comment]
Fixed it to base off the CI checks on `develop`/`master` right now.
