### ISSUE TITLE
Deployment Panel is not getting updated after contract deployment

### ISSUE THREAD

**Issue by xhulz** [trufflesuite/vscode-ext#134]
*** Problem
Deployment Panel is not getting updated after contract deployment even clicking on refresh button. Clicking over "No Contract Built/Deployed" an error message is displayed.

<img width="1681" alt="Screenshot 2022-07-08 at 10 14 17" src="https://user-images.githubusercontent.com/32708942/177973454-7d4a5386-3460-4e6c-9563-fc752a70e80f.png">

**Comment by michaeljohnbennett** [comment]
ok, I shall I have a look.

**Comment by michaeljohnbennett** [comment]
I think this is perhaps related to #135 raised by @acuarica?

**Comment by xhulz** [comment]
Hey @michaeljohnbennett,

Yes, exactly. @acuarica has been working on that :)

Thank you!
