### ISSUE TITLE
`Deploy Contracts` context menu fails when the selected contract is not directly in the `contracts` folder

### ISSUE THREAD

**Issue by acuarica** [trufflesuite/vscode-ext#135]
In the **Explorer - Truffle** view, the `Deploy Contracts` context menu fails if the contract to deploy is not directly inside the `contracts` folder, raising an  _Truffle configuration file not found_ error. The `truffle unbox optimism` has this kind of structure. For example

![issue87op-1657278945091](https://user-images.githubusercontent.com/4592980/177982200-16ce1cd5-4cd9-43fe-9af2-179391987551.gif)

On the other hand, if the contract is placed directly inside the `contracts` folder, the `Deploy Contracts` works as expected.

![issue87op-1657278962426](https://user-images.githubusercontent.com/4592980/177982247-b5fe2cdc-9936-446c-a76a-943cbdb5f972.gif)

**Comment by xhulz** [comment]
Hey @acuarica,

We are having to do a lot of treatments because the Workspace Library is not working on Windows 11. The issue is occurring inside this method, shown below. Feel free to fix that :)

![Screenshot 2022-07-08 at 12 33 44](https://user-images.githubusercontent.com/32708942/177985218-da7a8a98-8e1f-4418-8809-fc54c2f01076.png)

**Comment by acuarica** [comment]
Thanks for the heads up. I believe that the Windows 11 and this issue are different, the root cause for this issue being the contract build path has been hardcoded. 

![image](https://user-images.githubusercontent.com/4592980/177986365-1fd7fcb0-c41d-4326-b011-5ea6da53ffc8.png)

**Comment by michaeljohnbennett** [comment]
this was hardcoded at the beginning to get it working on base projects. Fixing this code to either have a function to resolve the build paths in monorepos or some other method would be the best idea now we have the ability to handle monorepos. @xhulz maybe able to point you in the direction of teh code that does that so you can fix this.

**Comment by acuarica** [comment]
The context menu `Deploy Contracts` was removed from the _Contract Explorer_ when applied to a single contract #177.

This issue was fixed in #179.
