### ISSUE TITLE
Fix `Truffle: Start Ganache` command when invoked from the command palette

### ISSUE THREAD

**Issue by acuarica** [trufflesuite/vscode-ext#138]
The `Truffle: Start Ganache` command (linked to **`truffle-vscode.startGanacheServer`** command id) raises a `Cannot start ganache server` error when invoked directly from the command palette. It actually displays a picker to allow the user to select the service to be started.

![truffle-sample-project-1657638940552](https://user-images.githubusercontent.com/4592980/178525392-024ce132-266b-4487-950d-82cde281fef3.gif)

Moreover, when the user selects `Truffle: Restart Ganache`, the pickers appears twice before failing with same error.

![truffle-sample-project-1657715317489](https://user-images.githubusercontent.com/4592980/178733643-0cb7affe-b777-4873-afce-2489dc86befe.gif)

On the other hand, when invoked within the `Truffle/Networks` view, it works correctly.

![truffle-sample-project-1657639147281](https://user-images.githubusercontent.com/4592980/178525682-fc0f1abf-772c-43aa-a5cc-65e9878d1e1d.gif)

**Comment by kevinbluer** [comment]
Great spot @acuarica!

**Comment by kevinbluer** [comment]
Just spotted that we also had this https://github.com/trufflesuite/vscode-ext/issues/68 (as opened by @xhulz a couple of months ago). I'll go ahead and close it in favor of this one given it's largely duplicative (and I think was more related to the extension activation lifecycle).
