### ISSUE TITLE
Improve the error notification when debugger encounters an error

### ISSUE THREAD

**Issue by kevinbluer** [trufflesuite/vscode-ext#143]
Currently, when attempting to start the debugger, if the Ganache (or equivalent) instance isn't running, it displays the following:

<img width="343" alt="Screen Shot 2022-07-13 at 2 28 31 PM" src="https://user-images.githubusercontent.com/210755/178815998-ad7bc497-32d7-4b7f-817d-0314934a6b76.png">
 
Let's change the text to something like the following: "Unable to start the debugger. It's possible that the node it's trying to connect to isn't running or is inaccessible. To troubleshoot, try the [debugging guide](https://trufflesuite.com/docs/vscode-ext/debugging-smart-contracts/) or [open a discussion](https://github.com/orgs/trufflesuite/discussions). Error message: `<insert-returned-error>`"

**Comment by frankiefab100** [comment]
I will like to fix this.

**Comment by kevinbluer** [comment]
Hey @frankiefab100, that would be awesome! Feel free to check out the [contributing guidelines](https://github.com/trufflesuite/vscode-ext/blob/develop/CONTRIBUTING.md) which should give a good overview of process, although feel free to ping here with any questions, etc too.

Thanks again and excited for the contribution 🥳

**Comment by frankiefab100** [comment]
> Hey @frankiefab100, that would be awesome! Feel free to check out the [contributing guidelines](https://github.com/trufflesuite/vscode-ext/blob/develop/CONTRIBUTING.md) which should give a good overview of process, although feel free to ping here with any questions, etc too.
> 
> Thanks again and excited for the contribution 🥳

Please which directory can I find this issue?

**Comment by kevinbluer** [comment]
Turns out it might not be as simple as what I first thought (although still not too tricky) 😄  From a quick review it looks like that error is actually coming from web3, specifically [this call](https://github.com/trufflesuite/vscode-ext/blob/develop/src/debugAdapter/transaction/transactionProvider.ts#L28) to `getBlockNumber()`. One approach could be to wrap it in a `try...catch` and include the above text in the error's message?

cc-ing @acuarica @michaeljohnbennett @xhulz for any additional takes.

**Comment by frankiefab100** [comment]
> Turns out it might not be as simple as what I first thought (although still not too tricky) 😄 From a quick review it looks like that error is actually coming from web3, specifically [this call](https://github.com/trufflesuite/vscode-ext/blob/develop/src/debugAdapter/transaction/transactionProvider.ts#L28) to `getBlockNumber()`. One approach could be to wrap it in a `try...catch` and include the above text in the error's message?
> 
> cc-ing @acuarica @michaeljohnbennett @xhulz for any additional takes.

okay, I will like to get everyone tagged here, their opinion/input on how to go about it.

**Comment by kevinbluer** [comment]
Hey @frankiefab100, heads up that this one actually got fixed in https://github.com/trufflesuite/vscode-ext/pull/170. As per my earlier comment it ended up being a little nuanced as the error was being thrown by [web3](https://github.com/ChainSafe/web3.js) so it was a case of catching it and [rethrowing with the improved error message](https://github.com/trufflesuite/vscode-ext/blob/922739b98ca611d64eb95124bcf42d4b6f4752f9/src/debugAdapter/transaction/transactionProvider.ts#L31-L35).

A few more [good first issues](https://github.com/trufflesuite/vscode-ext/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+) (and more coming shortly) if you're interested. Thanks again 🙏
