### ISSUE TITLE
Truffle for vscode not detecting nodejs 16.16.0 LTS

### ISSUE THREAD

**Issue by FalconX2022** [trufflesuite/vscode-ext#147]
Hello 
I'm new to this , I saw that there are some open issue for the same problem , it seems there is a work around to indicate the version 
can someone help or send me a link how to fix this issue ? 
Edit : using windows 10 
thanks

**Comment by kevinbluer** [comment]
Hey @FalconX2022, thanks for reaching out! Interesting, as Node 16 is definitely supported by the extension. We do have a [installation troubleshooting guide](https://trufflesuite.com/docs/vscode-ext/installation-guide/) which includes some details on installing Node on Windows, which could be worth a look.

Beyond that, would you be able to provide a screenshot(s) of where / how it's failing? E.g. if it's showing the Required Apps screen or something else?

**Comment by FalconX2022** [comment]
it seems that I had an old version of the build tools of code , I followed the guide you have indicated and downloaded the tools from 2022 and now seems to be ok 
thank you

**Comment by kevinbluer** [comment]
Awesome, thanks for the heads up @FalconX2022, glad it's resolved!
