### ISSUE TITLE
Implement fetch external sources feature to the debugger

### ISSUE THREAD

**Issue by kulho** [trufflesuite/vscode-ext#149]
Opened per request by @kevinbluer in #97 

Implement the fetch external sources option for the native vs code debugger. Feature from the truffle debugger in question: https://trufflesuite.com/blog/debugging-verified-external-contracts-with-truffle-debugger/

**Comment by kevinbluer** [comment]
Thanks again for raising / opening this @kulho! I was just discussing with a couple of folks on the team and we're going to begin scoping it during the next sprint (with a view to _hopefully_ implementing it during the following). We'll update in the thread here as things progress 👍

**Comment by gnidan** [comment]
Seems like there _might_ be a way to avoid writing to disk? Not sure if this works, but see [this SO answer](https://stackoverflow.com/a/55994114)

**Comment by kevinbluer** [comment]
@acuarica fancy having a dig into this one for [arbequina](https://github.com/orgs/trufflesuite/projects/28/views/1)?

**Comment by xhulz** [comment]
Hey @kevinbluer

I was thinking about on the first step, before the list of networks, put a selector with 2 options `Debug a local transaction` or `Fetch transaction from external network`. So in the next step we just need to filter the local and forked networks. What do you think?

Thank you

**Comment by acuarica** [comment]
Hi @kevinbluer and @xhulz for your suggestions. I've just pushed some improvements leaning toward Option 1. Currently the debugger can be started either from the `Debug Transaction` command or directly via the `Run and Debug` bar. In the future, it might be even triggered by the CLI if https://github.com/trufflesuite/vscode-ext/pull/231 gets merged.

I believe we need to provide mechanisms to enable/disable fetch external in each of these scenarios.

**Comment by kevinbluer** [comment]
Awesome, taking a look @acuarica! Also for reference, here's some transaction hashes for us to test with:

- First purchase of a Crytopunk: `0x65579455ac3227e7b3db72b4e359e988bb16cae6d26c88818d1a6991b478b274`
- Uniswap v3 deployment: `0xe881c43cd88063e84a1d0283f41ee5348239b259c0d17a7e2e4552da3f4b2bc7`
- Axie Infinity Ronin Bridge hack: `0xed2c72ef1a552ddaec6dd1f5cddf0b59a8f37f82bdda5257d9c7c37db7bb9b08`

**Comment by kevinbluer** [comment]
Just reviewed and looks good to me for now 👍 I have some thoughts around the broader UX for this but I still a bit fuzzy so this is great for now. I did tweak the copy a little as follows (happy to tweak further too):

<img width="598" alt="Screen Shot 2022-11-03 at 4 06 12 PM" src="https://user-images.githubusercontent.com/210755/199835378-e54fb87d-f1f5-46bd-83ea-e307f9a05699.png">

**Comment by xhulz** [comment]
Hey @acuarica!

Nice job! About https://github.com/trufflesuite/vscode-ext/pull/231 I'll merge it today :)

Cheers!

**Comment by acuarica** [comment]
> Just reviewed and looks good to me for now 👍 I have some thoughts around the broader UX for this but I still a bit fuzzy so this is great for now. I did tweak the copy a little as follows (happy to tweak further too):

I think we need to add a flag into the launch debug configuration to control the fetch external behavior. Then we can adapt the UI to set this flag as mentioned above. I see two potential behaviors:

1. `fetchExternal: boolean` defaults to `false`. The debugger always tries to fetch external regardless of the underlying network when this flag is set. This is similar to the `--fetch-external` flag in Truffle. The user needs to opt-in to enable this feature.
2. `disableFetchExternal/noFetchExternal: boolean` defaults to `false`. The debugger **only** tries to fetch external in a local forked network unless this flag is set. The user needs to opt-out to disable this feature.

Given said that, I would left this change for another PR.

**Comment by kevinbluer** [comment]
Just discussed with @xhulz and leaning towards #1 (e.g. `fetchExternal: boolean`), which he'll add to the Truffle CLI `--vscode` object that's getting passed over.

**Comment by acuarica** [comment]
Hi @kevinbluer, as discussed, here it's an example of a local (non-forked) transaction calling an external contract in a ganache forked instance. The example it's just getting the `balanceOf` [USDC](https://goerli.etherscan.io/address/0x2f3a40a3db8a7e3d09b0adfefbce4f6f81927557) for some hard-coded account. To sum up, fetch external _does_ make sense for local transactions, which makes lean towards _Option 2_ (https://github.com/trufflesuite/vscode-ext/issues/149#issuecomment-1303485176)

https://user-images.githubusercontent.com/4592980/200653659-38320cff-21f4-48f4-9b42-69998a54c35a.mp4

> The video it's a bit long because it's a proxy contract and I debugged the full transaction.

**Comment by xhulz** [comment]
@kevinbluer @acuarica,

As we said, I just implemented the parameter `fetchExternal` on URI Handler and in the configuration (PR #254). I've set its default value as `false`.

Once we have this PR merged, @acuarica you can change the debug routine in the best way that suits you :)

Cheers!

**Comment by kevinbluer** [comment]
Awesome, thanks for the confirmation @acuarica! @xhulz it might have been a bit unclear from the above, but would it be possible to switch the name of the parameter to `disableFetchExternal` (and still keep the default to `false`). Feel free to confirm from too @acuarica. Thanks again!

**Comment by acuarica** [comment]
> `[...]` would it be possible to switch the name of the parameter to `disableFetchExternal` (and still keep the default to false).
@kevinbluer @xhulz I can take care of it.
