### ISSUE TITLE
"Show Smart Contract Interaction Page" doesn't show in context menu

### ISSUE THREAD

**Issue by bbest-blockpass** [trufflesuite/vscode-ext#180]
After deploying my contract to my local ganache blockchain the "Show Smart Contract Interaction Page" option is not available.
I'm using Windows 10.

**Comment by kevinbluer** [comment]
Hey @bbest-blockpass, as mentioned [in this thread](https://github.com/trufflesuite/vscode-ext/issues/129#issuecomment-1178210500) this feature was actually deprecated, although it never got removed from the welcome page 🤦 Sorry about that!

We are actually working on a new approach to it that will be added to [Truffle Dashboard](https://trufflesuite.com/docs/truffle/getting-started/using-the-truffle-dashboard/) soon. In the interim, an alternative approach to interacting with your contracts is via `truffle console` (documentation [here](https://trufflesuite.com/docs/truffle/getting-started/using-truffle-develop-and-the-console/) if you're not familiar with it).
