### ISSUE TITLE
'truffle-vscode.newSolidityProject' not found 

### ISSUE THREAD

**Issue by zoltrader** [trufflesuite/vscode-ext#185]
'truffle-vscode.showWelcomePage' not found 
'truffle-vscode.newSolidityProject' not found 

**Basically, none of the truffle extension commands work**

Truffle v5.5.24 (core: 5.5.24)
Ganache v7.4.0
Solidity - 0.8.15 (solc-js)
Node v16.16.0
Web3.js v1.7.4

**Comment by michaeljohnbennett** [comment]
Hi @zoltrader is this on the latest release of the plugin?

Can you paste in the output from the `Truffle for VSCode` output channel as it might help pinpoint whats going on. 

To be sure, the truffle view will appear and other functions seem to show but no commands are loading?

Any screenshots you can send to figure out the problem would be appreciated.

**Comment by zoltrader** [comment]
Thank you for your respond, Michael.
Here is the output

Get version for required apps: node,npm,git,truffle,ganache
[Truffle: Execute command] v16.16.0
[Truffle: Execute command] npm[Truffle: Execute command]  WARN[Truffle: Execute command]  config global `--global`, `--local` are deprecated. Use `--location=global` instead.
[Truffle: Execute command] 8.11.0
[Truffle: Execute command] git version 2.37.1.windows.1
[Truffle: Execute command] Truffle v5.5.24 (core: 5.5.24)
[Truffle: Execute command] Ganache v7.4.0
[Truffle: Execute command] Solidity - 0.8.15 (solc-js)
Node v16.16.0
Web3.js v1.7.4
[Truffle: Execute command] ganache v7.4.0 (@ganache/cli: 0.5.0, @ganache/core: 0.5.0)
[checkApps] Current state for versions: [{"app":"node","isValid":true,"requiredVersion":{"max":"17.0.0","min":"14.0.0"},"version":"16.16.0"},{"app":"npm","isValid":true,"requiredVersion":{"max":"9.0.0","min":"6.14.15"},"version":"8.11.0"},{"app":"git","isValid":true,"requiredVersion":"2.10.0","version":"2.37.1"},{"app":"truffle","isValid":true,"requiredVersion":{"max":"6.0.0","min":"5.0.0"},"version":"5.5.24"},{"app":"ganache","isValid":true,"requiredVersion":{"max":"8.0.0","min":"6.0.0"},"version":"7.4.0"}] Invalid: false
[Truffle for VSCode] Cannot read properties of undefined (reading 'uri')

**Comment by zoltrader** [comment]
<img width="330" alt="image" src="https://user-images.githubusercontent.com/49073809/182071382-6cabe870-b6ae-4aa1-819e-1052b470c5dc.png">

**Comment by xhulz** [comment]
Hey @zoltrader, Thank you for reaching out to us :)

Could you please tell us which OS and version you are using? Just to clarify, did you try clicking on the Truffle logo in the left bar before calling the command?

Thank you again :)

![truffle-1659343134679](https://user-images.githubusercontent.com/32708942/182109678-4d055783-e150-425c-bcf5-924c944e1ee5.gif)

**Comment by zoltrader** [comment]
It's windows 11

<img width="230" alt="image" src="https://user-images.githubusercontent.com/49073809/182150316-e28dfc21-8753-4ef3-804a-9887a478b2eb.png">

**Comment by zoltrader** [comment]
I noticed where the problem was. For some reason the path to the workspace was lost!!!. It is working fine now.
Thank you

<img width="180" alt="image" src="https://user-images.githubusercontent.com/49073809/182156319-5e0d3f03-eb2d-473a-aefb-8e974e8052d6.png">
