### ISSUE TITLE
Have new project match truffle init

### ISSUE THREAD

**Issue by emilyJLin95** [trufflesuite/vscode-ext#194]
When I start a new Solidity project through the command palette, it should match the artifacts that are generated by `truffle init`

**Comment by acuarica** [comment]
Hi @emilyJLin95, thanks for sending this. Currently the `New Solidity Project` command, followed by the `Create basic project` option, unboxes the [`vscode-starter-box`](https://github.com/truffle-box/vscode-starter-box). Not sure what the intended outcome should be.

@kevinbluer what should it do?

**Comment by kevinbluer** [comment]
Likewise, thanks for opening @emilyJLin95! This has been on the radar to improve for a while. After briefly discussing with @acuarica earlier today, we landing on the following:

- Create empty project (_equivalent of `truffle init`_)
- Create sample project (_current [vscode-starter-box](https://github.com/truffle-box/vscode-starter-box) box with some enhancements_)
- Create project from Truffle Box (_which will launch another dropdown with the full list of all boxes_)

I'm also tempted to suggest we include the following, although would love input. There's definitely an argument to include these under Truffle boxes, although of course giving them some increased visibility would be pretty cool too.

- Create example NFT project
- Create example Token project
- Create example DAO project

Including the current dropdown for reference...

<img width="600" alt="Screen Shot 2022-08-09 at 3 43 45 PM" src="https://user-images.githubusercontent.com/210755/183757142-143130ad-a1b2-4dfa-8e68-bb65a2df9d69.png">

**Comment by acuarica** [comment]
I like the idea of including "most used" or "most relevant" boxes as first choices for the user.

Linking #25 since they are both related to having a list of boxes.

**Comment by kevinbluer** [comment]
Yeah I like the idea of having (default) sorting by most used / relevant. Perhaps along with a text based filter in the same way we have it in place to filter networks when deploying?

<img width="599" alt="Screen Shot 2022-08-10 at 10 52 08 AM" src="https://user-images.githubusercontent.com/210755/183955253-428c6b37-cbd7-4419-8622-31ea6f9a9f84.png">

Also thanks for linking #25, I'll go ahead and consolidate this detail under there shortly.

**Comment by kevinbluer** [comment]
cc @xhulz on this given it also ties into #25 which you're about to start work on. Let's discuss if any questions 👌

**Comment by xhulz** [comment]
Ok, thanks @kevinbluer!

**Comment by xhulz** [comment]
Hey @kevinbluer and @acuarica 

As suggested by you folks, i've moved the directory selection from the beginning of the flow to the end.

PR ref #226 

Thank you :)

**Comment by xhulz** [comment]
merged in PR #222
