### ISSUE TITLE
Running `truffle debug <txhash>` with appropriate flag (--vscode) triggers debugger to launch / run in VS Code

### ISSUE THREAD

**Issue by kevinbluer** [trufflesuite/vscode-ext#203]
Details to follow (although note it will also likely require a [Truffle CLI](https://github.com/trufflesuite/truffle) update) 

some other possible requirements:

- vscode command line shortcut would need to be installed perhaps `code ...`
- what would happen if the plugin was not installed in VScode?
- What would happen if vscode wasn't installed?
- if not using the cli shortcut, how do we reconcile the installed version?
- is this going to work on all platforms (win, osx, linux)

**Comment by xhulz** [comment]
PR ref: https://github.com/trufflesuite/vscode-ext/pull/261
