### ISSUE TITLE
Remove redundant txns from dialog after a redeploy

### ISSUE THREAD

**Issue by kevinbluer** [trufflesuite/vscode-ext#210]
## Issue

When you redeploy a contract without restarting the network, duplicate transactions show up in the dialog when selecting a `txhash` via `Truffle: Debug Transaction`, for example. Note that the "legacy" txns don't include the contract name.

<img width="601" alt="Screen Shot 2022-08-18 at 3 33 36 PM" src="https://user-images.githubusercontent.com/210755/185489938-06bfdb5a-0b22-4070-a507-b78bb15c7de6.png">

**Comment by xhulz** [comment]
ref PR #225
