### ISSUE TITLE
New Truffle / Ganache tabs incorrectly brought into focus

### ISSUE THREAD

**Issue by kevinbluer** [trufflesuite/vscode-ext#232]
The tabs added in #145 are incorrectly being brought into focus (see below for example). As discussed, perhaps let's remove the logic for the upcoming release and give some additional thought as to what should trigger it.

![metacoin-1-1664392568009](https://user-images.githubusercontent.com/210755/192871464-1dc4695d-f912-4d81-86a3-8662e76a64d9.gif)

**Comment by xhulz** [comment]
hey @kevinbluer,

I've pushed this PR to solve this problem. I just removed the line that was putting focus on truffle tab: https://github.com/trufflesuite/vscode-ext/pull/233

Thank you

**Comment by xhulz** [comment]
fixed on #233
