### ISSUE TITLE
Temporarily continue logging to the Truffle for VS Code output channel

### ISSUE THREAD

**Issue by kevinbluer** [trufflesuite/vscode-ext#234]
With #145 we disabled the Truffle for VS Code output channel in favor of the dedicated tabs (below). Since we're going to [hold off on the auto-focus](https://github.com/trufflesuite/vscode-ext/pull/233) let's continue to log to the `Truffle for VS Code` output channel AND the sub tabs under the new Truffle tab so as to mitigate the risk of any confusion to users.

<img width="523" alt="Screen Shot 2022-10-05 at 11 04 15 AM" src="https://user-images.githubusercontent.com/210755/194108038-0674b61d-ff98-4175-a5e5-7133e3ff0b28.png">

**Comment by xhulz** [comment]
PR ref: https://github.com/trufflesuite/vscode-ext/pull/237
