### ISSUE TITLE
Spurious closing bracket on "Create sample project" entry when creating a new project

### ISSUE THREAD

**Issue by kevinbluer** [trufflesuite/vscode-ext#235]
See the description on the second entry below...

<img width="600" alt="Screen Shot 2022-10-05 at 11 41 29 AM" src="https://user-images.githubusercontent.com/210755/194115238-a75dc3f0-1ead-443b-8c1e-956a6d7ab126.png">

**Comment by xhulz** [comment]
PR ref: #238
