### ISSUE TITLE
Intermittent (and incorrect) display of the dependencies splash screen

### ISSUE THREAD

**Issue by kevinbluer** [trufflesuite/vscode-ext#24]
The means with which it does the detection occasionally throws false negative(s) in that it doesn't correctly find the deps even though they're there

**Comment by ch4dwick** [comment]
> This is happening sometimes when the processes do not seem to gather the return values from the shell. I'm not sure why this happens but if the shell is spawning perhaps one instance is running some kind of update script (ohmyzsh for example) that might change the output from the command as it runs firstly. Just a theory.
> 
> Need to see if this is happening on Windows as we have only seen this on MacOS

I am running Ubuntu-based Pop_OS! and the issue is happening on my end. I'm using zsh with oh-my-posh/ohmyzsh.

**Comment by kevinbluer** [comment]
Hey @kevinbluer, super sorry for the delay in getting to this one! There's been a some changes to the logic in the dependency look checks that might resolve this if you're happy to try again? 

cc @xhulz for reference.

**Comment by ch4dwick** [comment]
> Hey @ch4dwick, super sorry for the delay in getting to this one! There's been a some changes to the logic in the dependency look checks that might resolve this if you're happy to try again?
> 
> cc @xhulz for reference.

I just updated to the latest copy and the issue still persists.

**Comment by ch4dwick** [comment]
> Thanks for trying again @ch4dwick and apologies for the issue! We have done some light testing on Ubuntu, although not Pop_OS specifically so there's a chance it's a distro specific issue. If you don't mind, would you mind sharing the extension's console output (select the console tab and "Truffle for VSCode" from the accompanying dropdown):
> 
> <img alt="Screen Shot 2022-07-21 at 10 19 49 AM" width="1197" src="https://user-images.githubusercontent.com/210755/180251205-b758e5a8-4643-469b-963f-a96eadb7d2ca.png">
> 
> This should tell us specifically what dependency(ies) are not being detected.
> 
> Lastly, just for reference, this is something we're going to be refactoring soon (#169) as you're not the first to experience it upside_down_face

Hey, I don't know what I did but I tried doing an npm -g update on my machine today but everything's working now:
Get version for required apps: node,npm,git,truffle,ganache
[Truffle: Execute command] v16.15.0
[Truffle: Execute command] 8.5.5
[Truffle: Execute command] git version 2.34.1
[Truffle: Execute command] Truffle v5.5.21 (core: 5.5.21)
[Truffle: Execute command] Ganache v7.2.0
[Truffle: Execute command] Solidity v0.5.16 (solc-js)

It was able to detect all of them. :)

One of the 2 things I did could have fixed it: 

1. Could be because I was using node 18.x.x. via nvm use --latest. I switched to nvm use --lts.
2. Updated truffle suite.

In any case, it appears it's not bugging me for missing installations. :)

**Comment by michaeljohnbennett** [comment]
Hey @ch4dwick there is some issues with node/npm versions and truffle right now.

LTS (v16.x) and NPM 6 is the most stable and will install fine, not sure about NPM 8 but if its working then great news!

The node versions and npm are requirements of the main truffle packages and not the extension itself, we are hoping to make this better in the future as its got to do with transient dependencies in truffle not always installing correctly on later versions of node/npm.

Sorry for the confusion and happy smart contract developing now!

**Comment by kevinbluer** [comment]
Likewise, thanks for the update @ch4dwick and that's great news! I'll go ahead close this one for now in favor of https://github.com/trufflesuite/vscode-ext/issues/169 (which is addressing the issue more holistically), but definitely feel free to open further issues or [discussions](https://github.com/orgs/trufflesuite/discussions/categories/vscode-extension) now you can actually use it 😅
