### ISSUE TITLE
Required app issues

### ISSUE THREAD

**Issue by ifsheldon** [trufflesuite/vscode-ext#271]
Hi! I'm new to using truffle to develop smart contracts and I want to use vscode, but the experience is a bit confusing, especially on the required apps. Here are a couple of issues I found.

Why do you need node.js to be below 17 while the LTS of node.js now is 18.12.1? Can I stick with my current lts node.js?

Another issue is about ganache. I installed it according to the official guide, which recommends me to install an App with UI instead of a CLI. As I understand, the UI app is basically the same as the CLI, but this extension cannot check the availability of the UI app, so I had to install the CLI. 

If I miss anything, just let me know. Thanks!

**Comment by acuarica** [comment]
Hi @ifsheldon, thanks for sharing your concerns.

> Why do you need node.js to be below 17 while the LTS of node.js now is 18.12.1? Can I stick with my current lts node.js?

Both Truffle and Ganache support Node 18. So, yes, you should be able to work with Node 18, even if the extension now requires a Node version below 18. We'll send a PR to support Node 18 within the extension.

> [...] but this extension cannot check the availability of the UI app, so I had to install the CLI.

Installing either the UI app or the CLI is matter of preference. The VS Code extension only requires the CLI to be installed, so you should be fine in this regard.

**Comment by acuarica** [comment]
Node 18 support should be included in #272.

**Comment by ifsheldon** [comment]
> Installing either the UI app or the CLI is matter of preference. The VS Code extension only requires the CLI to be installed, so you should be fine in this regard.

It will be great to avoid confusion (like "I installed Ganache according to the guide but why the extension told me it's not installed") if the environment is correctly set up if the extension can also check that the UI app is available. This should align better with the installation guide of Ganache.

**Comment by acuarica** [comment]
After discussing with @kevinbluer, we have decided to update the _Requirements Page_ to make clear that the extension depends on Ganache CLI, and not on Ganache UI. This will be fix in a new PR.

In any case, if you still want to connect to your own Ganache UI instance, you can do so by starting a Ganache UI instance and then go to the VS Code extension, _Networks_ view, under the `...` button, and _Connect to network_, for example

![truffle-sample-project-1669931437935](https://user-images.githubusercontent.com/4592980/205166523-6dde47d7-e4fa-49b9-9765-857d8122b1a0.gif)

**Comment by ifsheldon** [comment]
Yeah, I figured it out before. Thanks! I think you can also mention in the documentation of the extension that Ganache UI can work with the extension as well.

**Comment by acuarica** [comment]
Hi @ifsheldon, we just [released](https://github.com/orgs/trufflesuite/discussions/5766) a new version of the extension that includes both

- #272 and
- #274.

Regarding the documentation, we are going to discuss it internally.

**Comment by ifsheldon** [comment]
OK, thanks!
