### ISSUE TITLE
Review Telemetry settings and setup

### ISSUE THREAD

**Issue by acuarica** [trufflesuite/vscode-ext#285]
Review how to enable or disable sending Telemetry events from the extension. The currently used `enableTelemetry` setting has been deprecated in favor of `telemetryLevel`[1]. We need to honor this setting and/or include our own customized setting to be in sync with the rest of Truffle products. This is according to the _Telemetry extension authors guide_[2].

Moreover, we need to update our `README.md` to reflect any changes made. The section on _Telemetry_[3] is outdated as well.

Notice that the new `telemetryLevel` setting is an enum with values `all`, `error`,`crash` and `off`. Thus we can be more specific on the event that are being logged.

We might also want to consider using the new [`@vscode/extension-telemetry`](https://www.npmjs.com/package/@vscode/extension-telemetry) package. The extension currently uses [`vscode-extension-telemetry`](https://www.npmjs.com/package/vscode-extension-telemetry) which has been deprecated. Moreover the new package seems to have out-of-the-box support for the `telemetryLevel` flag.

See https://news.ycombinator.com/item?id=28812486 and https://github.com/microsoft/vscode/issues/134660 for a background discussion.

---

- [1] https://code.visualstudio.com/docs/supporting/faq#_how-to-disable-telemetry-reporting
- [2] https://code.visualstudio.com/api/extension-guides/telemetry
- [3] https://github.com/trufflesuite/vscode-ext#telemetry

**Comment by kevinbluer** [comment]
As discussed, the plan is to make it consistent with the rest of the suite and have a custom telemetry setting that's `off` by default. First pass at the wording for the settings entry:

- Title - Telemetry
- Description - Specifies whether to allow the collection of anonymous usage data
