### ISSUE TITLE
Unable to deploy contracts on Windows when path contains certain characters

### ISSUE THREAD

**Issue by emiridbest** [trufflesuite/vscode-ext#299]
after installing truffle extension, i ve been unable to deploy contracts.
keeps returninin error messages
"undefined:undefined contains invalid WIN32 path characters."
"Workspace root should be defined"

**Comment by acuarica** [comment]
Hi @emiridbest, thanks for reporting this. Would you be able to share some screenshot or short video to demonstrate this issue? Can you provide the version of your OS and `truffle`?

**Comment by emiridbest** [comment]
![Uploading 16740568635338867940895504861853.jpg…]()

**Comment by emiridbest** [comment]
Uploading 20230118_164924.mp4…

This is the error prompt when trying to deploy a contract

**Comment by emiridbest** [comment]
Uploading 20230118_164924.mp4…

This is the error prompt when trying to deploy a contract

**Comment by emiridbest** [comment]
Truffle for VS Code v5.7.3
WindowsOS  64bit, x64

**Comment by gnidan** [comment]
Thanks for opening this! You probably noticed, but your mp4/screenshots failed to upload. Could you maybe try uploading one or both of those to another service (IPFS maybe?)

Or if you can provide us with any kind of reproduction steps, we'd love to be able to get to the bottom of this for you. Sorry you ran into this problem!

**Comment by cds-amal** [comment]
Closing this for issue maintenance. If this is still a problem, please open a new issue. Thanks!
