### ISSUE TITLE
Truffle for vscode extension unable to install.

### ISSUE THREAD

**Issue by praizeroman** [trufflesuite/vscode-ext#305]
![IMG-20230311-WA0024](https://user-images.githubusercontent.com/79039317/224474072-1e424688-6722-48f7-a609-f81cd87e1b44.jpg)
I've tried to install Truffle on vscode from the extension, but I keep getting "error while installing Truffle for vscode extension, please check the log for more details". Then I'm advised to download manually, which I did but also got this error "NET::ERR_NAME_NOT_RESOLVED.

**Comment by kevinbluer** [comment]
Hey @praizeroman, just been doing some digging into this and it looks like it might be a network / connectivity issue. There's some steps [outlined here](https://github.com/microsoft/vscode/issues/99480#issuecomment-640810182) that could be worth trying...also are you able to install other extensions or is it just isolated to Truffle for VS Code?

**Comment by praizeroman** [comment]
i can install other extensions except "Ethereum security bundle" for reasons i don't know. and i don't think its a network issue cos i an access the site https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default 
![err](https://user-images.githubusercontent.com/79039317/224815358-1fd1b935-fb0f-4dd6-a244-c1eb9ca4c41a.jpg)
here is a log of the errors i encountered .

**Comment by kevinbluer** [comment]
Hmmm that's a bit of a weird one...can you confirm the following and I'll do a bit of additional digging:

- Operating System + version (looks like Windows from the screenshot)
- Visual Studio Code version

Also just to confirm, do you have any unusual network constraints in place (e.g. behind a restrictive firewall)?

**Comment by eggplantzzz** [comment]
closing this for issue maintenance - feel free to create a new issue if this is still a problem and you'd like to continue troubleshooting
