### ISSUE TITLE
Auth link not open

### ISSUE THREAD

**Issue by faixanmalik** [trufflesuite/vscode-ext#307]
auth link not open the authorized page that authorized connect infura to trufflesuit
thats happen when i try to signin infura from truffle vscode extension
the login page open and i correctly enter email and password and error below happen

this error here
request to https://prod.hydra.internal.infura.org/oauth2/auth/requests/login/accept?login_challenge=5306e2c85e294e7cac1b519a33d29b13 failed, reason: getaddrinfo ENOTFOUND prod.hydra.internal.infura.org

please try to fix this immediately
![screencapture-app-infura-io-login-2023-05-05-13_01_01](https://user-images.githubusercontent.com/117710738/236405894-9adea505-ef48-4156-b37b-ee7f227e434a.png)

**Comment by eggplantzzz** [comment]
Thanks for submitting this, we'll go ahead and investigate.

**Comment by faixanmalik** [comment]
i try to copy link and paste it another browser same thing happens

**Comment by faixanmalik** [comment]
is anyone here to solve my problem??????????????????

**Comment by faixanmalik** [comment]
is anyone here?????????

**Comment by faixanmalik** [comment]
no response from infura support??????

**Comment by kevinbluer** [comment]
Hi @faixanmalik, I've been doing some digging into this and am able to reproduce it on my side too (see below). I'm following up with the relevant teams to try and get a resolution in place and will loop back when I have an update. Thanks again for raising and patience while we get it resolved 👍 

![Screenshot 2023-05-04 at 12 51 25 PM](https://github.com/trufflesuite/vscode-ext/assets/210755/b3692b45-32b7-4371-92ac-1c2cdc2d5815)

**Comment by faixanmalik** [comment]
**@kevinbluer**  Thankx for replying can you please tell me that is this error is in your side too? when to try to login infura with vs code truffle extension?

**Comment by kevinbluer** [comment]
Correct @faixanmalik, I'm seeing it when trying to login to Infura via the extension.

**Comment by faixanmalik** [comment]
**@kevinbluer** ok thankx for it please fix it ass soon as possible

**Comment by faixanmalik** [comment]
@kevinbluer  i wanted to tell you something whenever you copy this link into new tab https://prod.hydra.internal.infura.org/oauth2/auth/requests/login/accept?login_challenge=5306e2c85e294e7cac1b519a33d29b13 
this page is not found.. 

the issue is in https://prod.hydra.internal.infura.org this domain this address is acutally not found in google 
when you signin using extension vs code send this link but because of  this domain ( https://prod.hydra.internal.infura.org ) is not exist that doesn't login

**Comment by kevinbluer** [comment]
Thanks for the additional detail @faixanmalik!

**Comment by kevinbluer** [comment]
Hey @faixanmalik, just to keep you in the loop...I raised with the appropriate team and there should hopefully a fix in place soon (will update as soon as I have more).

**Comment by faixanmalik** [comment]
Ok please fix it **@kevinbluer**  as soon as possible. and update me when this issue is fixed

**Comment by faixanmalik** [comment]
will you fix my issue **### @kevinbluer** ???

**Comment by faixanmalik** [comment]
ok thanks @kevinbluer this work now......
