### ISSUE TITLE
Requirements Screen - Reword instructions around installing and updating dependencies

### ISSUE THREAD

**Issue by michaeljohnbennett** [trufflesuite/vscode-ext#39]
We should have more instructions on needing to restart VSCode after dependencies have been installed due to PATH updates that may not be reflected in the VSCode when checking for updates.

There is also some issues on Windows regarding compiler chain installation, perhaps linking to the node-gyp installer page or the VS Build Tools link to install if people are having problems - is this for the wiki or readme or requirements page? @kevinbluer 

Possible link to wiki pages outling installation FAQ for each OS.

**Comment by kevinbluer** [comment]
Closing for issue maintenance 👍
