### ISSUE TITLE
Ganache dependency when 6.x installed (all good with v7.0.0-beta.0)

### ISSUE THREAD

**Issue by kevinbluer** [trufflesuite/vscode-ext#4]
Reasonable chance this is just me, but figured I'd get it down just in case 😅 

<img width="795" alt="Screen Shot 2021-11-23 at 11 03 07 AM" src="https://user-images.githubusercontent.com/210755/143070497-df7012a1-4a45-4ba0-b11a-a5fa0c687085.png">

**Comment by cds-amal** [comment]
Closing for issue maintenance
