### ISSUE TITLE
Inspecting global state while debugging incorrectly displays initial values

### ISSUE THREAD

**Issue by kevinbluer** [trufflesuite/vscode-ext#45]
When inspecting global state variables (either via the variable explorer or hovering over the variables in the editor), initial values will be shown until the values have been accessed. Note screenshot below wherein `InstanceOwner` is incorrectly showing `0x000...`.

<img width="976" alt="Screen Shot 2022-03-29 at 6 02 47 PM" src="https://user-images.githubusercontent.com/210755/160720606-345a7249-8613-4426-acf5-e0893de676a7.png">

Discussion with @gnidan highlighted that this is [known issue](https://github.com/trufflesuite/truffle/issues/2894) and the plan for is for a tweak to @truffle/debugger to provide a flag to indicate that the value has not yet been accessed. This will allow us to provide a meaningful message to the user (vs an incorrect value).

**Comment by michaeljohnbennett** [comment]
not in progress, now we have the fixes into released truffle this is probably ready to pick up.
