### ISSUE TITLE
Infura sign in timeout

### ISSUE THREAD

**Issue by kevinbluer** [trufflesuite/vscode-ext#50]
Awaiting additional repro steps, but @kuldeep23907 experienced a timeout when attempting to sign in to Infura (screenshots below).

![Screenshot 2022-03-31 at 11 45 46 AM](https://user-images.githubusercontent.com/210755/161646490-b5e48eb4-836c-4279-976e-ffeece937d18.jpg)

![Screenshot 2022-03-31 at 11 57 59 AM](https://user-images.githubusercontent.com/210755/161646492-f3f45731-3c27-4682-a135-c7c40f0fc796.jpg)

**Comment by haltman-at** [comment]
@kevinbluer I take it we haven't gotten those repro steps yet?

**Comment by kevinbluer** [comment]
Hey @haltman-at, nope not yet. I'll give Kuldeep a nudge.

**Comment by kevinbluer** [comment]
Closing for issue maintenance
