### ISSUE TITLE
Auto open the Truffle for VSCode extension output tab upon build

### ISSUE THREAD

**Issue by kevinbluer** [trufflesuite/vscode-ext#53]
When running a build via the right-click context menu, e.g.

![Screen Shot 2022-04-06 at 2 32 59 PM](https://user-images.githubusercontent.com/210755/162054746-024c4f6b-a9dd-459f-8069-f45521947889.png)

It would be both a neat productivity enhancement and an aid to new(er) users to the extension to have it automatically bring this tab into focus:

![Screen Shot 2022-04-06 at 2 33 09 PM](https://user-images.githubusercontent.com/210755/162054931-b42d260d-2268-4ba2-9051-8cbaf194dbdd.png)

Not sure if it's even possible per the VSCode extension API but worth some digging.

**Comment by xhulz** [comment]
Hey @kevinbluer,

This issue has already been resolved and merged. Perhaps we simply overlooked closing this one. Anyway, I'll close that, but if there are any issues, feel free to open it again.

Cheers!
