### ISSUE TITLE
Truffle Suite Installation: npm ERR! Error: EACCES: permission denied

### ISSUE THREAD

**Issue by xhulz** [trufflesuite/vscode-ext#58]
During the truffle suite installation, If the user has no permission on node_modules folder (e.g.: /usr/local/lib/node_modules/) we need to show a message warning him

`Running command
npm i -g  truffle@">=5.0.0 <6.0.0"
[Truffle: Execute command] npm[Truffle: Execute command]  ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/truffle
[Truffle: Execute command] npm ERR! [Truffle: Execute command] errno -13
[Truffle: Execute command] npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/truffle'
[Truffle: Execute command] npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/truffle'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
[Truffle: Execute command] npm ERR!   path: '/usr/local/lib/node_modules/truffle'
npm ERR! }`

**Comment by michaeljohnbennett** [comment]
this is noted comprehensively in the getting started docs for vscode on our fleek host. This is awaiting merging into main docs/website.

The issue has nothing to do with VSCode and is a user, on a mac, trying to install packages into a system level folder without using sudo, which is a no-no anyway.

Docs will recommend using a local install or nvm to handle this. system wide node installs are generally frowned upon and cause more problems than they are worth.

**Comment by michaeljohnbennett** [comment]
https://bafybeiey2fvq4oxdf4oupwu37aua3cgpi4v2au3brtunmg7jloqdkgprt4.on.fleek.co/docs/vscode-ext/installation-guide.html#tldr-2-node-is-hard-to-get-right-for-a-beginner-on-a-mac-

**Comment by xhulz** [comment]
Good  👍
