### ISSUE TITLE
Add a "Truffle: " prefix on context menu commands

### ISSUE THREAD

**Issue by kevinbluer** [trufflesuite/vscode-ext#72]
As per the following screenshot, "Solidity Visual Developer" adds a "Solidity: " prefix to its context menu commands. I feel this might be useful to include (see "Build Contracts", "Deploy Contracts") as it helps distinguish the commands. This is particularly useful when the context menus are quite busy.

<img width="286" alt="Screen Shot 2022-05-04 at 10 08 03 AM" src="https://user-images.githubusercontent.com/210755/166711975-2b9f1c40-aa63-4e1e-a1c2-7e28c0759f92.png">

**Comment by michaeljohnbennett** [comment]
Yeah, easy enough fix.

**Comment by NikolaiSch** [comment]
I will create a pull request tonight! working on it right now.

**Comment by kevinbluer** [comment]
Done #84
