### ISSUE TITLE
Ability to compile a single contract (via the right-click context menu)

### ISSUE THREAD

**Issue by kevinbluer** [trufflesuite/vscode-ext#83]
Now possible via https://github.com/trufflesuite/truffle/pull/5079 so we'd need to check the user has `v5.5.14` of Truffle. The menus could be updated to something like `Compile Single File` and `Compile All`.

**Comment by cds-amal** [comment]
Neat idea @kevinbluer !

**Comment by xhulz** [comment]
Close as completed via https://github.com/trufflesuite/vscode-ext/pull/177
