### ISSUE TITLE
Add support for multiple truffle config files (e.g. truffle-config.ovm.js)

### ISSUE THREAD

**Issue by kevinbluer** [trufflesuite/vscode-ext#92]
More detail to follow 🤝

**Comment by acuarica** [comment]
Hi @kevinbluer,

It seems there is partial support for multiple workspaces. It enables the user to select the config file to use. However both Contract Explorer and Deployments view do not reflect these multiple workspaces.

https://user-images.githubusercontent.com/4592980/181646876-bd6d44f6-ec4d-4ace-95a1-d9e249019334.mp4

We could leverage this mechanism to include other Truffle config files, _.e.g._, `truffle-config.ovm.js`, within a single workspace. However, there two issues we need to solve:

1. **What other Truffle config files should we look for?** Essentially, any `.js` file could be a Truffle config, so how does the extension know which files should be read as Truffle config? One solution could be to use the `truffle-config{,.*}.js` glob.
2. **Where the Contract Explorer and Deployments should take the data from?** In this scenario, _i.e._, multiple workspaces or multiple config files, they could add a top level item that represents the Truffle config file it was taken from.

**Comment by acuarica** [comment]
Here's a preview solving 
> 1. What other Truffle config files should we look for? [...]

https://user-images.githubusercontent.com/4592980/181650174-4122a267-9794-49e0-ba1d-85b6b15706f3.mp4
