### ISSUE TITLE
VSCode Plugin - Error occured in debug mode: No source file

### ISSUE THREAD

**Issue by marcpre** [trufflesuite/vscode-ext#95]
- [x] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

Hello,

I have installed the following versions:

```
[Truffle: Execute command] Truffle v5.5.5 (core: 5.5.5)
[Truffle: Execute command] Ganache v^7.0.3
[Truffle: Execute command] Solidity v0.5.16 (solc-js)
[Truffle: Execute command] Node v16.15.0
[Truffle: Execute command] Web3.js v1.5.3
Ubuntu 20.4
```

I am trying to debug my contract with the new vscode truffle plugin.

I get the following:

![image](https://user-images.githubusercontent.com/30902582/170818974-9cfb40b3-ee1c-405b-b3e5-9fd207db41f2.png)

My `truffle.config` looks like the following:

```
const path = require("path");

module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // to customize your Truffle configuration!
  contracts_build_directory: path.join(__dirname, "client/public/contract_abis"),
  networks: {
    development: {
      host: "127.0.0.1",
      port: 7545,
      network_id: "*"
    }
  },
  compilers: {
    solc: {
      version: "^0.8.0",    // Fetch exact version from solc-bin (default: truffle's version)
      // docker: true,        // Use "0.5.1" you've installed locally with docker (default: false)
      // settings: {          // See the solidity docs for advice about optimization and evmVersion
      //  optimizer: {
      //    enabled: false,
      //    runs: 200
      //  },
      //  evmVersion: "byzantium"
      // }
    }
  }
};
```

In contrast when running the same in the console it is working fine:

![image](https://user-images.githubusercontent.com/30902582/170819116-3661ae4c-64ab-46f9-8c86-517a94694135.png)

## Expected Behavior

The vscode debugger should start to debug the transaction.

It seems to me that my build directory is not found for the transactions.

Any suggestions what I am doing wrong?

I appreciate your replies!

**Comment by marcpre** [comment]
> @marcpre, this looks like a bug in the way the extension searches for files. Can you share a screenshot of the VS Code "Explorer" tab (Ctrl+Shift+E) showing the complete file-system tree for the project?

Hi,

find below my file directory:

![grafik](https://user-images.githubusercontent.com/30902582/171957833-9f03251a-9582-4870-978d-a604b4021b03.png)
![grafik](https://user-images.githubusercontent.com/30902582/171957888-cb10d1c6-a39a-4f18-a462-e7a6d5850563.png)

**Comment by marcpre** [comment]
> Hi @marcpre we have seen this happen occasionally and its very non-determinant in terms of reproducing it.
> 
> Do you have an example repo we can use to try and recreate this issue? Sometimes we see this happen when a set contract build files are sent to the debugger via the extension and the file paths do not get set for some reason or other. It's almost impossible to track this down unless we have a repo with the problem occurring it.
> 
> Thanks for the issue being raised as well.

Please find below my repository: https://github.com/marcpre/demo_javascript_real-world-nft.git

**Comment by cds-amal** [comment]
Hello @marcpre, is this still an issue?

**Comment by fainashalts** [comment]
Hi @marcpre thank you for opening this issue. As we haven't heard from you in a while we are closing it for maintenance. If this or another error arises, please feel free to open a new issue. Thanks!
