### ISSUE TITLE
Truffle configuration file not found 

### ISSUE THREAD

**Issue by wzquyin** [trufflesuite/vscode-ext#99]
After run "Truffle : New Solidity Project"->"Create basic project"
right click contracts/HelloBlockchain.sol->Build Contracts
Output :spawn C:\Windows\system32\cmd.exe ENOENT
right click contracts/HelloBlockchain.sol->Deploy Contracts
Output : Truffle configuration file not found 

It`s ok few days ago ,today outputs errors
I do nothing!
then I try reinstall ext ，truffle ..ganche,,node,npm，，，stills outputs errors

**Comment by wzquyin** [comment]
thanks ,
the errors only in 2.3.1,I install 2.2.1 is works ok

> Hi @wzquyin thank you for reaching out.
> 
> Thank you for let us know about it. We are working on it to fix as soon as possible.
> 
> Please, in this meantime, you can try opening the command palette and type: Truffle: Build Contract.
> 
> Thanks!

**Comment by xhulz** [comment]
Thank you again @wzquyin. We are working on it :)

We are keeping this issue opened and after we solved it, we'll let you know

Thanks!

**Comment by wzquyin** [comment]
update in 2.3.3 errors remain...

**Comment by xhulz** [comment]
Hi @wzquyin,

We'd like to know if the issue still persists after the release of the new versions.

Thank you! :)
